export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const GET_USERS = 'GET_USERS';
export const SET_USER_ANSWER = 'SET_USER_ANSWER';
export const ADD_USER_QUESTION = 'ADD_USER_QUESTION';